version: '3'

services:
  two-gadget:
    build: ./
    volumes:
      - ./share:/home/<redacted>:ro
      - ./xinetd:/etc/xinetd.d/two-gadget:ro
    ports:
      - "0000:0000"
    expose:
      - "0000"